### ISSUE TITLE
signature issue

### ISSUE THREAD

**Issue by deva123** [vigneshuvi/iOS-Signature-Capture#1]
how to give custom delegate. 

i have integrated the code with my app.  and  after signature it is not redirecting to previous page can you please guide me asap

**Comment by vigneshuvi** [comment]
Are you facing a issue in Objective-c or Swift?
Please refer my examples.

**Comment by deva123** [comment]
swift

**Comment by vigneshuvi** [comment]
Please refer my example. Go to this CaptureSignatureViewController.m and check captureSign method.

**Comment by arshadsk5** [comment]
In Swift Example, when i click on get sign button its is getting crash with error "fatal error: unexpectedly found nil while unwrapping an Optional value" . please check and let me know as soon as possible. thanks

**Comment by vigneshuvi** [comment]
@arshadsk5 Are you testing in iOS 10? I have converted the sample project and library into swift 3. Please try now and let me know if you face same issue again.

**Comment by arshadsk5** [comment]
its ok i had done some changes to the code, now it's working fine in swift 2. Thanks

**Comment by vigneshuvi** [comment]
Ok Thanks.
