### ISSUE TITLE
How can i get points array?

### ISSUE THREAD

**Issue by ismaiI1** [vigneshuvi/iOS-Signature-Capture#3]
Hi,

I need to get  array of points (x,y) from UIBezierPath in Obj-C. How can i get it?

![ekran resmi 2017-12-06 14 10 40](https://user-images.githubusercontent.com/8086679/33658961-97c98e44-da8f-11e7-9b58-62304840f93d.png)

**Comment by vigneshuvi** [comment]
After successfully saved signature, you can download it from NSUserDefaults.

```
    NSData *data = [[NSUserDefaults standardUserDefaults] objectForKey:USER_SIGNATURE_PATH];
    NSMutableArray *signPathArray = [NSKeyedUnarchiver unarchiveObjectWithData:data];
```

[Get Path Array - Example](https://github.com/vigneshuvi/iOS-Signature-Capture/blob/master/Examples/Objective-C/signature/signature/CaptureSignatureViewController.m#L39-L41)

**Comment by ismaiI1** [comment]
I can get Path array, but i need x and y coordinates of all points.

**Comment by vigneshuvi** [comment]
Find coordinates of path.

`-(void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self becomeFirstResponder];
    
    NSData *data = [[NSUserDefaults standardUserDefaults] objectForKey:USER_SIGNATURE_PATH];
    NSMutableArray *signPathArray = [NSKeyedUnarchiver unarchiveObjectWithData:data];
    [self.signatureView setPathArray:signPathArray];
    [self.signatureView setNeedsDisplay];
    
    for (UIBezierPath *path in signPathArray) {
        NSMutableArray *keyPoints = [NSMutableArray array];
        CGPathApply(path.CGPath, (__bridge void * _Nullable)(keyPoints), printPathXY);
    }
}

void printPathXY (void *info, const CGPathElement *element) {
    CGPathElementType type = element->type;
    CGPoint point = *element->points;
    if (type != kCGPathElementCloseSubpath)
    {
        if ((type == kCGPathElementAddLineToPoint) ||
            (type == kCGPathElementMoveToPoint))
                NSLog(@"x:%f, y:%f",point.x, point.y);
        else if (type == kCGPathElementAddQuadCurveToPoint)
            NSLog(@"x:%f, y:%f",point.x, point.y);
        else if (type == kCGPathElementAddCurveToPoint)
            NSLog(@"x:%f, y:%f",point.x, point.y);
    }
}
`

**Comment by vigneshuvi** [comment]
Find coordinates of path:

```
-(void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    [self becomeFirstResponder];
    
    NSData *data = [[NSUserDefaults standardUserDefaults] objectForKey:USER_SIGNATURE_PATH];
    NSMutableArray *signPathArray = [NSKeyedUnarchiver unarchiveObjectWithData:data];
    [self.signatureView setPathArray:signPathArray];
    [self.signatureView setNeedsDisplay];
    
    for (UIBezierPath *path in signPathArray) {
        NSMutableArray *keyPoints = [NSMutableArray array];
        CGPathApply(path.CGPath, (__bridge void * _Nullable)(keyPoints), printPathXY);
    }
}

void printPathXY (void *info, const CGPathElement *element) {
    CGPathElementType type = element->type;
    CGPoint point = *element->points;
    if (type != kCGPathElementCloseSubpath)
    {
        if ((type == kCGPathElementAddLineToPoint) ||
            (type == kCGPathElementMoveToPoint))
                NSLog(@"x:%f, y:%f",point.x, point.y);
        else if (type == kCGPathElementAddQuadCurveToPoint)
            NSLog(@"x:%f, y:%f",point.x, point.y);
        else if (type == kCGPathElementAddCurveToPoint)
            NSLog(@"x:%f, y:%f",point.x, point.y);
    }
}
```

**Comment by ismaiI1** [comment]
Thanks :) 👍
